// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
// >>>> DO NOT CHANGE THIS FILE! <<<<
// Change the json schema instead

package htlc

import "github.com/iotaledger/wasp/packages/wasmvm/wasmlib/go/wasmlib/wasmtypes"

const (
	ScName        = "htlc"
	ScDescription = "htlc"
	HScName       = wasmtypes.ScHname(0xee8a50f4)
)

const (
	ParamKey       = "key"
	ParamOwner     = "owner"
	ParamReceivder = "receivder"
	ParamSecret    = "secret"
	ParamTime      = "time"
	ParamValue     = "value"
)

const (
	ResultOwner = "owner"
	ResultValue = "value"
)

const (
	StateInitTime  = "initTime"
	StateOwner     = "owner"
	StateReceivder = "receivder"
	StateSecret    = "secret"
	StateTime      = "time"
	StateValue     = "value"
)

const (
	FuncInit         = "init"
	FuncSetOwner     = "setOwner"
	FuncSetReceivder = "setReceivder"
	FuncSetSecret    = "setSecret"
	FuncSetTime      = "setTime"
	FuncSetValue     = "setValue"
	FuncTransfer     = "transfer"
	FuncWithdraw     = "withdraw"
	ViewGetOwner     = "getOwner"
	ViewGetValue     = "getValue"
)

const (
	HFuncInit         = wasmtypes.ScHname(0x1f44d644)
	HFuncSetOwner     = wasmtypes.ScHname(0x2a15fe7b)
	HFuncSetReceivder = wasmtypes.ScHname(0x5fd98b09)
	HFuncSetSecret    = wasmtypes.ScHname(0x7ebcfec8)
	HFuncSetTime      = wasmtypes.ScHname(0xba1b35f9)
	HFuncSetValue     = wasmtypes.ScHname(0xce30e109)
	HFuncTransfer     = wasmtypes.ScHname(0xa15da184)
	HFuncWithdraw     = wasmtypes.ScHname(0x9dcc0f41)
	HViewGetOwner     = wasmtypes.ScHname(0x137107a6)
	HViewGetValue     = wasmtypes.ScHname(0x040813fd)
)
