// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
// >>>> DO NOT CHANGE THIS FILE! <<<<
// Change the json schema instead

package htlc

import "github.com/iotaledger/wasp/packages/wasmvm/wasmlib/go/wasmlib/wasmtypes"

type ImmutableInitParams struct {
	proxy wasmtypes.Proxy
}

func (s ImmutableInitParams) Owner() wasmtypes.ScImmutableAgentID {
	return wasmtypes.NewScImmutableAgentID(s.proxy.Root(ParamOwner))
}

type MutableInitParams struct {
	proxy wasmtypes.Proxy
}

func (s MutableInitParams) Owner() wasmtypes.ScMutableAgentID {
	return wasmtypes.NewScMutableAgentID(s.proxy.Root(ParamOwner))
}

type ImmutableSetOwnerParams struct {
	proxy wasmtypes.Proxy
}

func (s ImmutableSetOwnerParams) Owner() wasmtypes.ScImmutableAgentID {
	return wasmtypes.NewScImmutableAgentID(s.proxy.Root(ParamOwner))
}

type MutableSetOwnerParams struct {
	proxy wasmtypes.Proxy
}

func (s MutableSetOwnerParams) Owner() wasmtypes.ScMutableAgentID {
	return wasmtypes.NewScMutableAgentID(s.proxy.Root(ParamOwner))
}

type ImmutableSetReceivderParams struct {
	proxy wasmtypes.Proxy
}

func (s ImmutableSetReceivderParams) Receivder() wasmtypes.ScImmutableAddress {
	return wasmtypes.NewScImmutableAddress(s.proxy.Root(ParamReceivder))
}

type MutableSetReceivderParams struct {
	proxy wasmtypes.Proxy
}

func (s MutableSetReceivderParams) Receivder() wasmtypes.ScMutableAddress {
	return wasmtypes.NewScMutableAddress(s.proxy.Root(ParamReceivder))
}

type ImmutableSetSecretParams struct {
	proxy wasmtypes.Proxy
}

func (s ImmutableSetSecretParams) Secret() wasmtypes.ScImmutableHash {
	return wasmtypes.NewScImmutableHash(s.proxy.Root(ParamSecret))
}

type MutableSetSecretParams struct {
	proxy wasmtypes.Proxy
}

func (s MutableSetSecretParams) Secret() wasmtypes.ScMutableHash {
	return wasmtypes.NewScMutableHash(s.proxy.Root(ParamSecret))
}

type ImmutableSetTimeParams struct {
	proxy wasmtypes.Proxy
}

func (s ImmutableSetTimeParams) Time() wasmtypes.ScImmutableInt64 {
	return wasmtypes.NewScImmutableInt64(s.proxy.Root(ParamTime))
}

type MutableSetTimeParams struct {
	proxy wasmtypes.Proxy
}

func (s MutableSetTimeParams) Time() wasmtypes.ScMutableInt64 {
	return wasmtypes.NewScMutableInt64(s.proxy.Root(ParamTime))
}

type ImmutableSetValueParams struct {
	proxy wasmtypes.Proxy
}

func (s ImmutableSetValueParams) Value() wasmtypes.ScImmutableUint64 {
	return wasmtypes.NewScImmutableUint64(s.proxy.Root(ParamValue))
}

type MutableSetValueParams struct {
	proxy wasmtypes.Proxy
}

func (s MutableSetValueParams) Value() wasmtypes.ScMutableUint64 {
	return wasmtypes.NewScMutableUint64(s.proxy.Root(ParamValue))
}

type ImmutableTransferParams struct {
	proxy wasmtypes.Proxy
}

func (s ImmutableTransferParams) Key() wasmtypes.ScImmutableHash {
	return wasmtypes.NewScImmutableHash(s.proxy.Root(ParamKey))
}

func (s ImmutableTransferParams) Secret() wasmtypes.ScImmutableHash {
	return wasmtypes.NewScImmutableHash(s.proxy.Root(ParamSecret))
}

type MutableTransferParams struct {
	proxy wasmtypes.Proxy
}

func (s MutableTransferParams) Key() wasmtypes.ScMutableHash {
	return wasmtypes.NewScMutableHash(s.proxy.Root(ParamKey))
}

func (s MutableTransferParams) Secret() wasmtypes.ScMutableHash {
	return wasmtypes.NewScMutableHash(s.proxy.Root(ParamSecret))
}
